<?php
function bakery_user_menu() {
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_new_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}
 

function welcome_new_user() {
	return 'welcome_new_user';
}

function bakery_user_login($edit, $account, $category) {
    $_GET['destination'] = 'welcome_new_user';
}
